title: Zircolite generic
order: 21
backends:
    - sqlite
logsources:
    cisco:
        product: cisco
        conditions:
            sourcetype: 'cisco*'
    dns:
        category: dns
        conditions:
            tag: "dns"
    firewall:
        category: firewall
        conditions:
            tag: 'network' 
    proxy:
        category: proxy
        conditions:
            tag: 'proxy'
    webserver:
        category: webserver
        conditions:
            tag: 'web'
    process_creation:
        category: process_creation
        product: windows
        conditions:
            EventID: 4688
        rewrite:
            product: windows
            service: security
    registry_event_win:
        category: registry_event
        product: windows
        conditions:
            EventID: 4657
            OperationType:
                - 'New registry value created'
                - 'Existing registry value modified'
            Channel: 'Security'
    windows:
        product: windows
    windows-application:
        product: windows
        service: application
        conditions:
            Channel: 'Application'
    windows-security:
        product: windows
        service: security
        conditions:
            Channel: 'Security'
    windows-system:
        product: windows
        service: system
        conditions:
            Channel: 'System'
    windows-sysmon:
        product: windows
        service: sysmon
        conditions:
            Channel: 'Microsoft-Windows-Sysmon/Operational'
    windows-powershell:
        product: windows
        service: powershell
        conditions:
            Channel: 'Microsoft-Windows-PowerShell/Operational'
    windows-classicpowershell:
        product: windows
        service: powershell-classic
        conditions:
            Channel: 'Windows PowerShell'
    windows-taskscheduler:
        product: windows
        service: taskscheduler
        conditions:
            Channel: 'Microsoft-Windows-TaskScheduler/Operational'
    windows-wmi:
        product: windows
        service: wmi
        conditions:
            Channel: 'Microsoft-Windows-WMI-Activity/Operational'
    windows-dns-server:
        product: windows
        service: dns-server
        conditions:
            Channel: 'DNS Server'
    windows-dns-server-audit:
        product: windows
        service: dns-server-audit
        conditions:
            Channel: 'Microsoft-Windows-DNS-Server/Audit'
    windows-driver-framework:
        product: windows
        service: driver-framework
        conditions:
            Channel: 'Microsoft-Windows-DriverFrameworks-UserMode/Operational'
    windows-ntlm:
        product: windows
        service: ntlm
        conditions:
            Channel: 'Microsoft-Windows-NTLM/Operational'
    windows-dhcp:
        product: windows
        service: dhcp
        conditions:
            Channel: 'Microsoft-Windows-DHCP-Server/Operational'
    windows-defender:
        product: windows
        service: windefend
        conditions:
            Channel: 
                - 'Microsoft-Windows-Windows Defender/Operational'
                - 'Microsoft-Windows-Windows Defender/WHC'
    windows-defender-product:
        product: windows_defender
        conditions:
            Channel: 
                - 'Microsoft-Windows-Windows Defender/Operational'
                - 'Microsoft-Windows-Windows Defender/WHC'
    windows-applocker:
        product: windows
        service: applocker
        conditions:
            Channel:
                - 'Microsoft-Windows-AppLocker/MSI and Script'
                - 'Microsoft-Windows-AppLocker/EXE and DLL'
                - 'Microsoft-Windows-AppLocker/Packaged app-Deployment'
                - 'Microsoft-Windows-AppLocker/Packaged app-Execution'
    windows-msexchange-management:
        product: windows
        service: msexchange-management
        conditions:
            Channel: 'MSExchange Management'
fieldmappings:
    Image: NewProcessName
    ParentImage: ParentProcessName
    ServiceFileName: ImagePath
    ProcessCommandline: CommandLine
    ComputerName: Computer
    MachineName: Computer
    userIdentity.arn: user_arn